### ISSUE TITLE
404 page and re-writting

### ISSUE THREAD

**Issue by trenyture** [kelyvin/express-env-example#1]
Hi, thanks you a lot for your architecture, it's really great, clean and easy to develop with it.

I just met some errors while I was trying to make my app.

First, when I started the Node Script, it gives me this error : `server.create is not a function` Well I find a solution re-writting the `server/index.js` file.

You put the functions directly in the module.exports and I prefer to keep the same logic as the others files, initializing functions Create and Start and then sending them to the module.exports. So my file looks like : 

```
function create(config) {
}
function start() {
}
module.exports = {
    start: start,
    create: create
};

```
Then I have another error that I can't solve... Before, I used to work with the `server.use(function(req,res){})` to check all the pages that are not defined, but I don't really know how to do with your architecture.

I tried to put in the `server/routes/index.js` after all my differents routes a code like this : 
```
/*404*/
server.use(function(req,res){
	res.status(404);
	res.render('404');
});
```

But now every pages I want to connect send me to my 404 page... is there anyway to correct this?
I would be so greatful,

Thanks

**Comment by trenyture** [comment]
Ok I would have tryed some more intempts...

I found my solution, sorry, I replace : 
```
/*404*/
server.use(function(req,res){
	res.status(404);
	res.render('404');
});
```
by : 
```
/*404*/
server.use('*', errorRoute);
```

Then I create a `routes/error` and a `controllers/error` where I put my function which render a 404 status with the 404 page to display.

Thanks a lot again and sorry for the disagreement.

**Comment by kelyvin** [comment]
No problem. To start up the project, all you need to run is `npm start` at the root directory of the project. Did that not work for you?

**Comment by trenyture** [comment]
Yeah, I tryed, and with your project it worked, but I wanted to copy it to my project and maybe I did something wrong with the router... I don't know... But it's working now, thanks you :)
